name: auspice-docs
channels:
  - conda-forge
dependencies:
  - make
  - recommonmark
  - sphinx
  - nodejs # server-side math rendering
  - pip
  - pip:
    - nextstrain-sphinx-theme>=2022.5
    - sphinx-autobuild
    - sphinx-markdown-tables
    - sphinx-argparse
    - pygments>=2.12.0  # For JSON with comments
    - sphinxcontrib-katex>=0.9.10 # math rendering